version: "2"

run:
  #  concurrency: 1
  timeout: 5m

linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - godox
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - paralleltest
    - perfsprint
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    revive:
      severity: warning
      enable-all-rules: true
      rules:
        - name: argument-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: file-header
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: unexported-naming
          disabled: true
        - name: add-constant
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: deep-exit
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: nested-structs
          disabled: true
        - name: confusing-results
          disabled: true
        - name: empty-lines
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: banned-characters
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: var-naming
          arguments:
            - [ ]
            - [ ]
            - [ { "skipPackageNameChecks": true } ]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  fix: true
