version: 2

snapshot:
  version_template: "{{ .FullCommit }}-SNAPSHOT"

builds:
  - id: "podproxy"
    main: "./cmd/podproxy"
    binary: "podproxy"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{.ModulePath}}/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: archive
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: internal/config/defaults.yaml
        dst: .
        strip_parent: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: podproxy
    ids:
      - archive
    homepage: "https://github.com/entwico/podproxy"
    description: "Kubernetes pod proxy that routes traffic through pod port-forwarding"
    license: "MIT"
    directory: Formula
    commit_msg_template: "chore: update {{ .ProjectName }} formula to {{ .Tag }}"
    extra_install: |
      (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
    service: |
      run [opt_bin/"podproxy", "--config", etc/"podproxy/config.yaml"]
      keep_alive true
      log_path var/"log/podproxy.log"
      error_log_path var/"log/podproxy.log"
      working_dir var
    caveats: |
      Configuration file:
        #{etc}/podproxy/config.yaml

      A default config is installed if one does not already exist.
      Edit it before starting the service:
        $EDITOR #{etc}/podproxy/config.yaml

      To start podproxy as a background service:
        brew services start #{name}

      To stop the service:
        brew services stop #{name}

      Logs are written to:
        #{var}/log/podproxy.log
    repository:
      owner: entwico
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

release:
  github:
    owner: entwico
    name: podproxy
  prerelease: auto
