version: 2

snapshot:
  version_template: "{{ .FullCommit }}-SNAPSHOT"

builds:
  - id: "podproxy"
    main: "./cmd/podproxy"
    binary: "podproxy"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{.ModulePath}}/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: archive
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: podproxy
    ids:
      - archive
    homepage: "https://github.com/entwico/podproxy"
    description: "Kubernetes pod proxy that routes traffic through pod port-forwarding"
    license: "MIT"
    directory: Formula
    commit_msg_template: "chore: update {{ .ProjectName }} formula to {{ .Tag }}"
    repository:
      owner: entwico
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

release:
  github:
    owner: entwico
    name: podproxy
  prerelease: auto
