version: "3"
output: "group"

vars:
  BUILD_DIR: dist

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - task: clean
      - task: node:build
      - goreleaser build --clean --snapshot

  node:build:
    dir: integrations/node
    env:
      NODE_OPTIONS: ""
    cmds:
      - pnpm install --frozen-lockfile
      - node build.mjs
      - mkdir -p ../../internal/nodeproxy/embed
      - cp dist/proxy.mjs ../../internal/nodeproxy/embed/proxy.mjs
      - cp dist/proxy.cjs ../../internal/nodeproxy/embed/proxy.cjs

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  test:
    cmds:
      - task: clean
      - task: node:build
      - mkdir -p {{.BUILD_DIR}}
      - go test -v -race -coverprofile=./{{.BUILD_DIR}}/coverage.out ./...
      - go tool cover -html=./{{.BUILD_DIR}}/coverage.out -o ./{{.BUILD_DIR}}/coverage.html

  lint:
    cmds:
      - task: node:build
      - golangci-lint version
      - golangci-lint run
