version: "3"
output: "group"

vars:
  BUILD_DIR: dist
  GOLANGCI_LINT: github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.10.1
  GORELEASER: github.com/goreleaser/goreleaser/v2@v2.13.3
  GOLANGCI_LINT_CMD: '{{if .CI}}golangci-lint{{else}}go run {{.GOLANGCI_LINT}}{{end}}'
  GORELEASER_CMD: '{{if .CI}}goreleaser{{else}}go run {{.GORELEASER}}{{end}}'

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - task: clean
      - task: node:build
      - '{{.GORELEASER_CMD}} build --clean --snapshot'

  node:build:
    dir: integrations/node
    env:
      NODE_OPTIONS: ""
    cmds:
      - pnpm install --frozen-lockfile
      - node build.mjs
      - mkdir -p ../../internal/nodeproxy/embed
      - cp dist/proxy.mjs ../../internal/nodeproxy/embed/proxy.mjs
      - cp dist/proxy.cjs ../../internal/nodeproxy/embed/proxy.cjs

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  test:
    cmds:
      - task: clean
      - task: node:build
      - mkdir -p {{.BUILD_DIR}}
      - go test -v -race -coverprofile=./{{.BUILD_DIR}}/coverage.out ./...
      - go tool cover -html=./{{.BUILD_DIR}}/coverage.out -o ./{{.BUILD_DIR}}/coverage.html

  lint:
    cmds:
      - task: node:build
      - '{{.GOLANGCI_LINT_CMD}} version'
      - '{{.GOLANGCI_LINT_CMD}} run'
